FastBlog/config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root to: 'blog/posts#index'


  namespace :authors do
    get '/account' => 'accounts#edit', as: :account
    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
    resources :posts do
     put 'publish' => 'posts#publish', on: :member
     put 'unpublish' => 'posts#unpublish', on: :member
   end
  end

  scope module: 'blog' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post


  end

  end

FastBlog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def display_error_messages
    errors.full_messages.join('. ') << '.' if errors.any?
  end
end

FastBlog/app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  validates_presence_of :name, on: :update

  def change_password(attributes)
    update(password: attributes[:new_password], password_confirmation: attributes[:new_password_confirmation])
  end

  def gravatar_image_url
    "https://www.gravatar.com/avatar/#{gravatar_hash}"
  end

  def display_name
    if name.present?
      name
    else
      'Author'
    end
  end

  private

  def gravatar_hash
    Digest::MD5.hexdigest(email.downcase)
  end
end

FastBlog/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  description      :text
#  slug             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  banner_image_url :string
#  author_id        :integer
#  published        :boolean          default(FALSE)
#  published_at     :datetime
#

class Post < ActiveRecord::Base

  acts_as_taggable # Alias for acts_as_taggable_on :tags
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :author

  PER_PAGE = 9.freeze

  scope :most_recent, -> { order(published_at: :desc) }
  scope :published, -> { where(published: true) }
  scope :recent_paginated, -> (page) { most_recent.paginate(page: page, per_page: PER_PAGE) }
  scope :with_tag, -> (tag) do
    tagged_with(tag) if tag.present?
  end

  scope :list_for, -> (page, tag) do
      recent_paginated(page).with_tag(tag)
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def display_day_published
     if published_at.present?
       "Published #{published_at.strftime('%-b %-d, %Y')}"
     else
       "Not published yet"
     end
  end

  def publish
    update(published: true, published_at: Time.now)
  end

  def unpublish
    update(published: false, published_at: nil)
  end

end

FastBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout 'author'

end

FastBlog/app/controllers/author_controller.rb
class AuthorController < ApplicationController
  before_action :authenticate_author!
end

FastBlog/app/controllers/authors/accounts_controller.rb
module Authors
  class AccountsController < AuthorController

    def edit
    end

    def update_info
      if current_author.update(author_info_params)
        flash[:success] = 'Successfully changed info'
      else
        flash[:danger] = current_author.display_error_messages
      end
      redirect_to authors_account_path
    end

    def change_password
            author = current_author
      if author.valid_password?(author_password_params[:current_password])
        if author.change_password(author_password_params)
          flash[:success] = 'Succesfully changed password'
        else
          flash[:danger] = author.display_error_messages
        end
      else
        flash[:danger] = 'Current assword was incorrect'
      end
      redirect_to authors_account_path
    end

    private

    def author_info_params
      params.require(:author).permit(:name, :email, :bio)
    end

    def author_password_params
      params.require(:author).permit(:current_password, :new_password, :new_password_confirmation)
    end
  end
end

FastBlog/app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    # GET /posts
    # GET /posts.json
    def index
      @posts = current_author.posts.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.posts.new
    end

    # GET /posts/1/edit
    def edit
    end

    def publish
      @post.publish
      redirect_to authors_posts_url
    end

    def unpublish
      @post.unpublish
      redirect_to authors_posts_url
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
      end
  end

end

FastBlog/app/controllers/blog/pages_controller.rb
module Blog
  class PagesController < BlogController

    def about
    end

    def contact
    end

  end

end

FastBlog/app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < BlogController

    # GET /posts
    # GET /posts.json
    def index
      @posts = storage.list_for(params[:page], params[:tag])
    end


    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = storage.friendly.find(params[:id])
    end

    private

    def storage
      Post.published
    end

  end

end

FastBlog/app/controllers/blog_controller.rb
class BlogController < ApplicationController

end

FastBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

FastBlog/app/helpers/posts_helper.rb
module PostsHelper
end

FastBlog/app/views/authors/accounts/edit.html.erb
<div class="row">

  <!-- Basic Info -->
  <div class="col-md-6">
    <%= form_tag authors_info_path, method: :put do %>
      <%= fields_for :author do |f| %>
          <div class="card">
            <ul class="list-group list-group-flush">
              <dev class="card-block">
                <div class="card-title">
                  Basic info
                </div>
              </dev>
              <li class="list-group-item">
                <%= image_tag(current_author.gravatar_image_url) %>
              </li>
              <li class="list-group-item">
                <div class="field">
                  <%= f.label :name %><br>
                  <%= f.text_field :name, value: current_author.name, class: "form-control form-control-md-4", type: "text"%>
                </div>
              </li>
              <li class="list-group-item">
                <div class="field">
                  <%= f.label :email %><br>
                  <%= f.email_field :email, value: current_author.email, class: "form-control form-control-md-4", type: "text" %>
                </div>
              </li>
              <li class="list-group-item">
                <div class="field">
                  <%= f.label :bio %><br>
                  <%= f.text_area :bio, value: current_author.bio, class: "form-control form-control-md-4", type: "text"%>
                </div>
              </li>
              <li class="list-group-item">
                <%= f.submit "Upadate info", class: 'btn btn-primary' %>
              </li>
            </ul>
          </div>
          <% end %>
      <% end %>
    </div>
  <!-- Change password -->

  <div class="col-md-6">
    <%= form_tag authors_change_password_path, method: :put do %>
    <%= fields_for :author do |f| %>
        <div class="card">
          <ul class="list-group list-group-flush">
            <dev class="card-block">
              <div class="card-title">
                  Change password
              </div>
            </dev>
            <li class="list-group-item">
              <div class="password-field" >
                <%= f.label :current_password %><br>
                <%= f.password_field :current_password, class: "form-control form-control-md-4", type: "password"%>
              </div>
            </li>
            <li class="list-group-item">
              <div class="password-field">
                <%= f.label :new_password %><br>
                <%= f.password_field :new_password, class: "form-control form-control-md-4", type: "password" %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="password-field">
                <%= f.label :new_password_confirmation %><br>
                <%= f.password_field :new_password_confirmation, class: "form-control form-control-md-4", type: "password"%>
              </div>
            </li>
            <li class="list-group-item">
              <%= f.submit "Change password", class: 'btn btn-warning' %>
            </li>
          </ul>
        </div>
      <% end %>
    <% end %>
</div>

FastBlog/app/views/authors/posts/_form.html.erb
<%= form_for(post, url: url) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">

      <div class="card">
        <div class="card-header">
          <% if @post.new_record? %>
            <h4 class="card-title">New post</h3>
          <%else%>
            <h4 class="card-title">
              <b>Edit</b>
              <span class="thin-text"><%= @post.title %></span>
            </h4>
          <%end%>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="field">
              <%= f.label :title %><br>
              <%= f.text_field :title, class: "form-control form-control-md-4", type: "text"%>
            </div>

          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label :banner_image_url %><br>
              <%= f.text_field :banner_image_url, class: "form-control form-control-md-4", type: "text" %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label :description %><br>
              <%= f.text_area :description, class: "form-control form-control-md-4", type: "text"%>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label 'Tags' %><br>
              <%= f.text_area :tag_list, class: "form-control form-control-md-4", type: "text"%>
            </div>
          </li>
          <li class="list-group-item">
              <div class="actions">
                <%= f.submit "Save blog post", class: 'btn btn-success btn-lg btn-block'%>
              </div>
          </li>
        </ul>
      </div>

    <% if @post.persisted? %>
      <%= link_to 'Show', @post%> |
    <%end%>
    <%= link_to 'Back', authors_posts_path %>


    </div>
    <div class="col-md-8">

      <div class="field">
        <%= f.text_area :body %>
      </div>

    </div>
  </div>


<% end %>

FastBlog/app/views/authors/posts/_post.html.erb
<tr>
  <td><%= link_to post.title, authors_post_path(post) %></td>
  <td></td>
  <% if post.published? %>
    <td><%= link_to 'Unpublish', unpublish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-primary' %></td>
  <% else %>
    <td><%= link_to 'Publish', publish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-success' %></td>
  <% end %>
  <td><%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-sm btn-warning' %></td>
  <td><%= link_to 'Remove', authors_post_path(post), method: :delete, data: { confirm: 'Are you sure?'},  class: 'btn btn-sm btn-danger' %></td>
</tr>

FastBlog/app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:author, 'active') %>

<%= render 'form', post: @post ,url: authors_post_url(@post)  %>

FastBlog/app/views/authors/posts/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:author, 'active') %>

<div class="row">
  <div>
    <%= link_to 'New post', new_authors_post_path, class: 'btn btn-primary btn-lg' %>
  </div>
  <br>
  <br>
  <br>
  <table class="table table-striped">
    <tr>
      <th colspan="5"> Title</th>
    </tr>
    <%= render @posts %>
  </table>
</div>

FastBlog/app/views/authors/posts/new.html.erb
<% provide(:page_title, 'New Post') %>
<% provide(:author, 'active') %>

<%= render 'form', post: @post, url: authors_posts_url %>

FastBlog/app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:author, 'active') %>

<div>
  <%= link_to 'Edit', edit_authors_post_path(@post), class: 'btn btn-sm btn-warning' %>
  <%= link_to 'Remove', authors_post_path(@post), method: :delete, data: { confirm: 'Are you sure?'},  class: 'btn btn-sm btn-danger' %>
</div>
<div class="row">
  <div class ="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center">
    <h1><%= @post.title %></h1>
    <p><%= @post.display_day_published %></p>
    <%= @post.body.html_safe %>
  </div>
</div>

FastBlog/app/views/blog/pages/about.html.erb
<% provide(:about_active, 'active') %>

FastBlog/app/views/blog/pages/contact.html.erb
<% provide(:contact_active, 'active') %>

FastBlog/app/views/blog/posts/_post.html.erb
<div class='col-sm-6 col-lg-4'>
  <div class="card">
    <%= link_to post do %>
      <div class="card-topper" style='background-image: url(<%= post.banner_image_url %>);'></div>
    <%end%>
    <div class="card-block">
      <h4 class="card-title"><%= link_to post.title, post %></h4>
      <p><%= raw post.tags.map { |t| link_to t.name, posts_path(tag: t.name)}.join(', ') %></p>
      <p class="published-date"><%= post.display_day_published %></p>
      <%= link_to post do %>
        <p class="card-text"><%= truncate(post.description, lenght: 130) %></p>
      <%end%>
    </div>
  </div>
</div>

FastBlog/app/views/blog/posts/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:blog_active, 'active') %>

<div class="row">
  <%= render @posts %>
</div>

<div class="apple_pagination">
  <%= will_paginate @posts, container: false %>
</div>

FastBlog/app/views/blog/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:blog_active, 'active') %>

<div class="row">
  <div class ="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center">
    <h1><%= @post.title %></h1>
    <p><%= @post.display_day_published %></p>
    <%= @post.body.html_safe %>

    <div class="author-bio">
      <%= image_tag(@post.author.gravatar_image_url) %>
      <h4><%= @post.author.name %></h4>
      <h6 class="bio"><%= @post.author.bio%></h6>
    </div>

  </div>
</div>

<div class="col-md-8 offset-md-2">
  <div id="disqus_thread"></div>
  <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

  <script>
  /**
  *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
  *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

  var disqus_config = function () {
    this.page.url = '<%= request.original_url %>';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @post.slug %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  };

  (function() { // DON'T EDIT BELOW THIS LINE
  var d = document, s = d.createElement('script');
  s.src = 'https://fast-blog.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
})();
</script>

</div>

FastBlog/app/views/layouts/_navbar.html.erb
<div class="collapse" id="exCollapsingNavbar">
  <div class="collapse-bg p-a-1">
    <div class='card'>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
        </li>
        <% if author_signed_in? %>
          <li class="list-group-item">
            <%= link_to 'My posts', authors_posts_path, class: "nav-link #{yield(:author)}" %>
          </li>
          <li class="list-group-item">
            <%= link_to 'Logout', authors_posts_path, class: "nav-link #{yield(:author)}" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<nav class="navbar navbar-light bg-light">
  <div class='container'>
    <a class='navbar-brand' href='/'>
      Fast<span class='light'>blog</span>
    </a>
    </button>
    <ul class="nav navbar-nav pull-sm-right hidden-xs-down">
      <li class="nav-item">
        <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
      </li>
      <% if author_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle <%= yield(:author) %>" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_author.display_name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'My posts', authors_posts_path, class: "dropdown-item" %>
            <%= link_to 'Account', authors_account_path, class: "dropdown-item " %>
            <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% end %>
    </ul>
  </div>
</nav>

FastBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:page_title) %> | FastBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/navbar' %>
  <div class="container <%= controller_name %> <%= action_name %>">
  <%= yield %>
  </div>
</body>
</html>

FastBlog/app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:page_title) %> | FastBlog</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
</head>

<body>
  <%= render 'layouts/navbar' %>
  <div class="container <%= controller_name %> <%= action_name %>">
    <% if flash.any? %>
      <% flash.keys.each do |key| %>
        <div class="alert alert-<%= key.to_s %> alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[key] %>
        </div>
      <%end%>
    <%end%>
  <%= yield %>
  </div>
</body>
</html>

FastBlog/app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:page_title) %> | FastBlog</title>
  <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700|Montserrat:300,400,700" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/navbar' %>
  <div class="container <%= controller_name %> <%= action_name %>">
  <%= yield %>
  </div>
</body>
</html>

FastBlog/app/views/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:blog_active, 'active') %>

<div class="row">
  <div class ="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center">
    <h1><%= @post.title %></h1>
    <p><%= @post.display_day_published %></p>
    <%= @post.body %>
  </div>
</div>